version: '3'
services:
  parking-manager-service-python:
    build:
      context: .
      dockerfile: Dockerfile
    image: parking-manager-service-python:dev-latest
    environment:
      - RUN_ENV=DEV
      - LOGGER_LEVEL=DEBUG
    ports:
      - 5000:5000
    command: make run

networks:
  default:
    external:
      name: dev_network
